apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rajuj6
  name: rajuj6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rajuj6
  strategy: {}
  template:
    metadata:
      labels:
        app: rajuj6
    spec:
      containers:
        - image: rajuj6/intro
          name: rajuj6
          ports:
            - containerPort: 5292
          resources: {}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rajuj6
  name: rajuj6
spec:
  ports:
    - name: "5292"
      port: 852920
      targetPort: 5292
  selector:
    app: rajuj6
  type: NodePort

